#!/usr/bin/env php
<?php

if (!$loader = @include __DIR__.'/vendor/autoload.php') {
    die('You must set up the project dependencies, run the following commands:'.PHP_EOL.
        'curl -s http://getcomposer.org/installer | php'.PHP_EOL.
        'php composer.phar install --dev'.PHP_EOL);
}

use UN\Locode\Builder\Builder;

$builder = new Builder();
$builder->run();